image:
  name: hashicorp/terraform:1.16
  entrypoint: [""]


# adding reset stage
workflow:
  rules:
    # RESET pipeline
    - if: '$PIPELINE_MODE == "reset"'

    # Normal deployment
    - if: '$PIPELINE_MODE == "deploy"'

    # Default: normal deployment on main
    - if: '$CI_COMMIT_BRANCH == "main"'



stages:
  - init
  - validate
  - plan_staging
  - apply_staging
  - approval
  - plan_production
  - apply_production
  - destroy

# test
before_script:
  - terraform --version
  - export AWS_REGION="${AWS_DEFAULT_REGION:-eu-west-3}"
  - |
    if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
      echo "ERROR: AWS credentials (AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY) are missing in CI!"
      echo "Ensure group variables exist under 'code-keeper' and are marked 'protected: false' if running on an unprotected branch."
      exit 1
    fi
  # - printf '%s\n' "$TFVARS_STAGING_FILE" > terraform.tfvars
  - terraform init 
# test new infra 
# 1. INIT STAGE
terraform_init:
  stage: init
  script:
    - echo "Terraform initialization successful."
    - terraform version
  rules:
  - if: '$PIPELINE_MODE == "deploy" && $CI_COMMIT_BRANCH == "main"'

# 2. VALIDATE STAGE
terraform_validate:
  stage: validate
  script:
    - terraform validate
    - echo "Validation passed."
  rules:
  - if: '$PIPELINE_MODE == "deploy" && $CI_COMMIT_BRANCH == "main"'

# 3. PLAN STAGE
plan_staging:
  stage: plan_staging
  script:
    - printf '%s\n' "$TFVARS_STAGING_FILE" > terraform.tfvars
    - echo "--------------------------------STAGING-------------------------------------"
    - cat terraform.tfvars
    - echo "----------------------------------------------------------------------------------"
    - terraform workspace select -or-create staging
    
    - terraform plan -out=tfplan-staging
  artifacts:
    name: "tfplan-staging-$CI_COMMIT_SHORT_SHA"
    paths:
      - tfplan-staging
    expire_in: 1 hour
  rules:
    - if: '$PIPELINE_MODE == "deploy" && $CI_COMMIT_BRANCH == "main"'

# 4. APPLY TO STAGING
apply_staging:
  stage: apply_staging

  environment:
    name: staging
  
  needs:
    - job: plan_staging
      artifacts: true
  
  script:
    - terraform workspace select -or-create staging
    - echo "Applying infrastructure changes to STAGING environment..."
    - terraform apply -auto-approve tfplan-staging
    - echo "Staging apply completed successfully."

  rules:
    - if: '$PIPELINE_MODE == "deploy" && $CI_COMMIT_BRANCH == "main"'

# # "-------------------------------------------------------------------"
# # "-------------------------------------------------------------------"
# # "-----------------------------PRODUCTION-----------------------------"
# # "-------------------------------------------------------------------"
# # "-------------------------------------------------------------------"


# 5. PLAN TO PRODUCTION

plan_production:
  stage: plan_production

  script:
    - printf '%s\n' "$TFVARS_PROD_FILE" > terraform.tfvars
    - terraform workspace select -or-create production
    - terraform plan -out=tfplan-production

  artifacts:
    paths:
      - tfplan-production
    expire_in: 1 hour

  rules:
    - if: '$PIPELINE_MODE == "deploy" && $CI_COMMIT_BRANCH == "main"'

# 6. MANUAL APPROVAL GATE
# test it
production_approval:
  stage: approval

  environment:
    name: production

  script:
    - echo "Production deployment approved by $GITLAB_USER_LOGIN at $(date)."
  
  when: manual

  allow_failure: false
  rules:
    - if: '$PIPELINE_MODE == "deploy" && $CI_COMMIT_BRANCH == "main"'

# changing 1

# 7. APPLY TO PRODUCTION
apply_production:
  stage: apply_production

  environment:
    name: production

  needs:
    - job: production_approval
      artifacts: true
    - job: plan_production
      artifacts: true

  script:
    - echo "Creating PRODUCTION terraform.tfvars..."
    - printf '%s\n' "$TFVARS_PROD_FILE" > terraform.tfvars

    - echo "-----> Terraform production variables:"
    - echo "----------------------------------------------------------------------------------"
    - cat terraform.tfvars
    - echo "----------------------------------------------------------------------------------"
    - terraform workspace select -or-create production

    - echo "Applying infrastructure changes to PRODUCTION environment..."

    #- terraform plan -out=tfplan-production
    
    - terraform apply -auto-approve tfplan-production

    - echo "Production apply completed successfully."

  rules:
    - if: '$PIPELINE_MODE == "deploy" && $CI_COMMIT_BRANCH == "main"'

# 7A. AUTOMATIC DESTROY ON FAILURE
# destroy_on_failure:
#   stage: destroy
#   script:
#     - echo "Pipeline failure detected! Triggering automatic resource cleanup..."
#     - terraform workspace select staging || true
#     - terraform destroy -input=false -auto-approve
#   when: on_failure
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "main"'

# 7B. MANUAL CLEANUP / DESTROY STAGE.
# destroy_manual:
#   stage: destroy
#   script:
#     - echo "Manual destroy triggered..."
#     - terraform destroy -input=false -auto-approve
#   when: manual
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "main"'
destroy_staging:
  stage: destroy

  script:
    - printf '%s\n' "$TFVARS_STAGING_FILE" > terraform.tfvars
    - terraform workspace select staging
    - terraform destroy -input=false -auto-approve

  when: manual

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'


# test domain name 
destroy_production:
  stage: destroy

  script:
    - printf '%s\n' "$TFVARS_PROD_FILE" > terraform.tfvars
    - terraform workspace select production
    - terraform destroy -input=false -auto-approve

  when: manual
  #test xx
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

# stage 

reset_staging:
  stage: destroy

  script:
    - echo "=========================================="
    - echo "RESET MODE"
    - echo "DESTROYING STAGING"
    - echo "=========================================="

    - printf '%s\n' "$TFVARS_STAGING_FILE" > terraform.tfvars

    - terraform workspace select staging

    - terraform plan -destroy -out=destroy-staging.tfplan

    - terraform apply -auto-approve destroy-staging.tfplan

    - echo "=========================================="
    - echo "STAGING DESTROYED"
    - echo "=========================================="

  rules:
    - if: '$PIPELINE_MODE == "reset" && $CI_COMMIT_BRANCH == "main"'


reset_production:
  stage: destroy

  needs:
    - job: reset_staging

  script:
    - echo "=========================================="
    - echo "RESET MODE"
    - echo "DESTROYING PRODUCTION"
    - echo "=========================================="

    - printf '%s\n' "$TFVARS_PROD_FILE" > terraform.tfvars

    - terraform workspace select production

    - terraform plan -destroy -out=destroy-production.tfplan

    - terraform apply -auto-approve destroy-production.tfplan

    - echo "=========================================="
    - echo "PRODUCTION DESTROYED"
    - echo "=========================================="

  rules:
    - if: '$PIPELINE_MODE == "reset" && $CI_COMMIT_BRANCH == "main"'