image:
  name: hashicorp/terraform:1.16
  entrypoint: [""]

stages:
  - destroy

before_script:
  - terraform --version
  - export AWS_REGION="${AWS_DEFAULT_REGION:-eu-west-3}"

  - |
    if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
      echo "ERROR: AWS credentials are missing!"
      exit 1
    fi

  - terraform init


destroy_staging:
  stage: destroy

  script:
    - echo "=========================================="
    - echo "DESTROYING STAGING"
    - echo "=========================================="

    - printf '%s\n' "$TFVARS_STAGING_FILE" > terraform.tfvars

    - terraform workspace select staging

    - terraform plan -destroy -out=destroy-staging.tfplan

    - terraform apply -auto-approve destroy-staging.tfplan

    - echo "STAGING DESTROYED"


destroy_production:
  stage: destroy

  script:
    - echo "=========================================="
    - echo "DESTROYING PRODUCTION"
    - echo "=========================================="

    - printf '%s\n' "$TFVARS_PROD_FILE" > terraform.tfvars

    - terraform workspace select production

    - terraform plan -destroy -out=destroy-production.tfplan

    - terraform apply -auto-approve destroy-production.tfplan

    - echo "PRODUCTION DESTROYED"