#!/bin/bash
# scripts/generate-imports.sh
set -e

REGION="us-east-1"
PREFIX="cloud-design"
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
IMPORTS_FILE="imports.tf"

echo "# Auto-generated by generate-imports.sh — do not edit manually" > $IMPORTS_FILE
echo "" >> $IMPORTS_FILE

echo "Account: $ACCOUNT_ID | Region: $REGION | Prefix: $PREFIX"
echo "---"

import_if_exists() {
  local TO=$1
  local ID=$2
  if [ -n "$ID" ] && [ "$ID" != "None" ] && [ "$ID" != "null" ] && [ "$ID" != "" ]; then
    echo "✅ Importing: $TO → $ID"
    printf 'import {\n  to = %s\n  id = "%s"\n}\n\n' "$TO" "$ID" >> $IMPORTS_FILE
  else
    echo "⏭️  Skipping (not found): $TO"
  fi
}

# ── VPC ──────────────────────────────────────
VPC_ID=$(aws ec2 describe-vpcs \
  --filters "Name=tag:Name,Values=${PREFIX}-vpc" \
  --region $REGION \
  --query 'Vpcs[0].VpcId' --output text 2>/dev/null || echo "")
import_if_exists "aws_vpc.main" "$VPC_ID"

# ── DHCP OPTIONS ─────────────────────────────
DHCP_ID=$(aws ec2 describe-dhcp-options \
  --filters "Name=tag:Name,Values=${PREFIX}-dhcp" \
  --region $REGION \
  --query 'DhcpOptions[0].DhcpOptionsId' --output text 2>/dev/null || echo "")
import_if_exists "aws_vpc_dhcp_options.main" "$DHCP_ID"

if [ -n "$VPC_ID" ] && [ "$VPC_ID" != "None" ]; then
  DHCP_ASSOC=$(aws ec2 describe-vpcs \
    --vpc-ids "$VPC_ID" --region $REGION \
    --query 'Vpcs[0].DhcpOptionsId' --output text 2>/dev/null || echo "")
  import_if_exists "aws_vpc_dhcp_options_association.main" "${VPC_ID}/${DHCP_ASSOC}"
fi

# ── SUBNETS ───────────────────────────────────
declare -A SUBNET_TAGS=(
  ["public_a"]="${PREFIX}-public-subnet-a"
  ["public_b"]="${PREFIX}-public-subnet-b"
  ["private_a"]="${PREFIX}-private-subnet-a"
  ["private_b"]="${PREFIX}-private-subnet-b"
)
for TF_NAME in public_a public_b private_a private_b; do
  SUBNET_ID=$(aws ec2 describe-subnets \
    --filters "Name=tag:Name,Values=${SUBNET_TAGS[$TF_NAME]}" \
    --region $REGION \
    --query 'Subnets[0].SubnetId' --output text 2>/dev/null || echo "")
  import_if_exists "aws_subnet.${TF_NAME}" "$SUBNET_ID"
done

# ── INTERNET GATEWAY ──────────────────────────
IGW_ID=$(aws ec2 describe-internet-gateways \
  --filters "Name=tag:Name,Values=${PREFIX}-igw" \
  --region $REGION \
  --query 'InternetGateways[0].InternetGatewayId' --output text 2>/dev/null || echo "")
import_if_exists "aws_internet_gateway.main" "$IGW_ID"

# ── NAT GATEWAY + EIP ─────────────────────────
NAT_ID=$(aws ec2 describe-nat-gateways \
  --filter "Name=tag:Name,Values=${PREFIX}-nat" "Name=state,Values=available" \
  --region $REGION \
  --query 'NatGateways[0].NatGatewayId' --output text 2>/dev/null || echo "")
import_if_exists "aws_nat_gateway.main" "$NAT_ID"

EIP_ALLOC=$(aws ec2 describe-addresses \
  --filters "Name=tag:Name,Values=${PREFIX}-nat-eip" \
  --region $REGION \
  --query 'Addresses[0].AllocationId' --output text 2>/dev/null || echo "")
import_if_exists "aws_eip.nat" "$EIP_ALLOC"

# ── ROUTE TABLES ──────────────────────────────
PUBLIC_RT_ID=$(aws ec2 describe-route-tables \
  --filters "Name=tag:Name,Values=${PREFIX}-public-rt" "Name=vpc-id,Values=${VPC_ID}" \
  --region $REGION \
  --query 'RouteTables[0].RouteTableId' --output text 2>/dev/null || echo "")
import_if_exists "aws_route_table.public" "$PUBLIC_RT_ID"

PRIVATE_RT_ID=$(aws ec2 describe-route-tables \
  --filters "Name=tag:Name,Values=${PREFIX}-private-rt" "Name=vpc-id,Values=${VPC_ID}" \
  --region $REGION \
  --query 'RouteTables[0].RouteTableId' --output text 2>/dev/null || echo "")
import_if_exists "aws_route_table.private" "$PRIVATE_RT_ID"

# Route table associations
for ASSOC in public_a public_b; do
  SUBNET_ID=$(aws ec2 describe-subnets \
    --filters "Name=tag:Name,Values=${SUBNET_TAGS[$ASSOC]}" \
    --region $REGION \
    --query 'Subnets[0].SubnetId' --output text 2>/dev/null || echo "")
  if [ -n "$SUBNET_ID" ] && [ "$SUBNET_ID" != "None" ] && [ -n "$PUBLIC_RT_ID" ] && [ "$PUBLIC_RT_ID" != "None" ]; then
    ASSOC_ID=$(aws ec2 describe-route-tables \
      --route-table-ids "$PUBLIC_RT_ID" --region $REGION \
      --query "RouteTables[0].Associations[?SubnetId=='${SUBNET_ID}'] | [0].RouteTableAssociationId" \
      --output text 2>/dev/null || echo "")
    import_if_exists "aws_route_table_association.${ASSOC}" "$ASSOC_ID"
  fi
done

for ASSOC in private_a private_b; do
  SUBNET_ID=$(aws ec2 describe-subnets \
    --filters "Name=tag:Name,Values=${SUBNET_TAGS[$ASSOC]}" \
    --region $REGION \
    --query 'Subnets[0].SubnetId' --output text 2>/dev/null || echo "")
  if [ -n "$SUBNET_ID" ] && [ "$SUBNET_ID" != "None" ] && [ -n "$PRIVATE_RT_ID" ] && [ "$PRIVATE_RT_ID" != "None" ]; then
    ASSOC_ID=$(aws ec2 describe-route-tables \
      --route-table-ids "$PRIVATE_RT_ID" --region $REGION \
      --query "RouteTables[0].Associations[?SubnetId=='${SUBNET_ID}'] | [0].RouteTableAssociationId" \
      --output text 2>/dev/null || echo "")
    import_if_exists "aws_route_table_association.${ASSOC}" "$ASSOC_ID"
  fi
done

# ── SECURITY GROUPS — alb, app, db, gateway, queue ──
declare -A SG_TAGS=(
  ["alb"]="${PREFIX}-alb-sg"
  ["app"]="${PREFIX}-app-sg"
  ["db"]="${PREFIX}-db-sg"
  ["gateway"]="${PREFIX}-gateway-sg"
  ["queue"]="${PREFIX}-queue-sg"
)
for TF_NAME in alb app db gateway queue; do
  SG_ID=$(aws ec2 describe-security-groups \
    --filters "Name=tag:Name,Values=${SG_TAGS[$TF_NAME]}" "Name=vpc-id,Values=${VPC_ID}" \
    --region $REGION \
    --query 'SecurityGroups[0].GroupId' --output text 2>/dev/null || echo "")
  import_if_exists "aws_security_group.${TF_NAME}" "$SG_ID"
done

# ── ALB + TARGET GROUP + LISTENERS ───────────
ALB_ARN=$(aws elbv2 describe-load-balancers \
  --names "${PREFIX}-alb" --region $REGION \
  --query 'LoadBalancers[0].LoadBalancerArn' --output text 2>/dev/null || echo "")
import_if_exists "aws_lb.main" "$ALB_ARN"

# Filter by correct VPC to avoid importing stale TG from old VPC
TG_ARN=$(aws elbv2 describe-target-groups \
  --names "${PREFIX}-gateway-tg" --region $REGION \
  --query "TargetGroups[?VpcId=='${VPC_ID}'].TargetGroupArn | [0]" \
  --output text 2>/dev/null || echo "")
import_if_exists "aws_lb_target_group.gateway" "$TG_ARN"

if [ -n "$ALB_ARN" ] && [ "$ALB_ARN" != "None" ]; then
  HTTP_ARN=$(aws elbv2 describe-listeners \
    --load-balancer-arn "$ALB_ARN" --region $REGION \
    --query 'Listeners[?Port==`80`].ListenerArn | [0]' --output text 2>/dev/null || echo "")
  import_if_exists "aws_lb_listener.http" "$HTTP_ARN"

  HTTPS_ARN=$(aws elbv2 describe-listeners \
    --load-balancer-arn "$ALB_ARN" --region $REGION \
    --query 'Listeners[?Port==`443`].ListenerArn | [0]' --output text 2>/dev/null || echo "")
  import_if_exists "aws_lb_listener.https" "$HTTPS_ARN"
fi

# ── ACM ───────────────────────────────────────
ACM_ARN=$(aws acm list-certificates --region $REGION \
  --query 'CertificateSummaryList[0].CertificateArn' --output text 2>/dev/null || echo "")
import_if_exists "aws_acm_certificate.self_signed" "$ACM_ARN"

# ── ECR ───────────────────────────────────────
declare -A ECR_REPOS=(
  ["gateway"]="${PREFIX}/api-gateway-app"
  ["billing_app"]="${PREFIX}/billing-app"
  ["billing_db"]="${PREFIX}/billing-db"
  ["billing_queue"]="${PREFIX}/billing-queue"
  ["inventory_app"]="${PREFIX}/inventory-app"
  ["inventory_db"]="${PREFIX}/inventory-db"
)
for TF_NAME in gateway billing_app billing_db billing_queue inventory_app inventory_db; do
  REPO_NAME="${ECR_REPOS[$TF_NAME]}"
  REPO_EXISTS=$(aws ecr describe-repositories \
    --repository-names "$REPO_NAME" --region $REGION \
    --query 'repositories[0].repositoryName' --output text 2>/dev/null || echo "")
  import_if_exists "aws_ecr_repository.${TF_NAME}" "$REPO_NAME"
done

# ── ECS CLUSTER ───────────────────────────────
ECS_ARN=$(aws ecs describe-clusters \
  --clusters "${PREFIX}-cluster" --region $REGION \
  --query 'clusters[?status==`ACTIVE`] | [0].clusterArn' --output text 2>/dev/null || echo "")
import_if_exists "aws_ecs_cluster.main" "$ECS_ARN"

# ── ECS SERVICES ──────────────────────────────
declare -A ECS_SVCS=(
  ["gateway"]="${PREFIX}-api-gateway-service"          # does not exist → will be skipped
  ["billing_app"]="${PREFIX}-billing-app-service"      # ← corrected
  ["inventory_app"]="${PREFIX}-inventory-app-service"  # ← corrected
  ["rabbitmq"]="${PREFIX}-rabbitmq-service"            # will be skipped if not found
)
for TF_NAME in gateway billing_app inventory_app rabbitmq; do
  SVC_NAME="${ECS_SVCS[$TF_NAME]}"
  SVC_EXISTS=$(aws ecs describe-services \
    --cluster "${PREFIX}-cluster" --services "$SVC_NAME" --region $REGION \
    --query 'services[?status==`ACTIVE`] | [0].serviceName' --output text 2>/dev/null || echo "")
  # Use verified name, not assumed
  if [ -n "$SVC_EXISTS" ] && [ "$SVC_EXISTS" != "None" ]; then
    import_if_exists "aws_ecs_service.${TF_NAME}" "${PREFIX}-cluster/${SVC_NAME}"
  else
    echo "⏭️  Skipping (not found): aws_ecs_service.${TF_NAME}"
  fi
done

# ── CLOUDWATCH LOG GROUPS ─────────────────────
declare -A LOG_GROUPS=(
  ["gateway"]="/ecs/${PREFIX}-api-gateway"
  ["billing_app"]="/ecs/${PREFIX}-billing"
  ["inventory_app"]="/ecs/${PREFIX}-inventory"
  ["rabbitmq"]="/ecs/${PREFIX}-rabbitmq"
)
for TF_NAME in gateway billing_app inventory_app rabbitmq; do
  LOG_NAME="${LOG_GROUPS[$TF_NAME]}"
  LOG_EXISTS=$(aws logs describe-log-groups \
    --log-group-name-prefix "$LOG_NAME" --region $REGION \
    --query 'logGroups[0].logGroupName' --output text 2>/dev/null || echo "")
  import_if_exists "aws_cloudwatch_log_group.${TF_NAME}" "$LOG_EXISTS"
done

# ── RDS ───────────────────────────────────────
# Only import subnet group if it belongs to the correct VPC
DB_SUBNET_VPC=$(aws rds describe-db-subnet-groups \
  --db-subnet-group-name "${PREFIX}-db-subnet-group" --region $REGION \
  --query 'DBSubnetGroups[0].VpcId' --output text 2>/dev/null || echo "")

if [ "$DB_SUBNET_VPC" == "$VPC_ID" ]; then
  import_if_exists "aws_db_subnet_group.main" "${PREFIX}-db-subnet-group"
else
  echo "⏭️  Skipping aws_db_subnet_group.main — wrong VPC ($DB_SUBNET_VPC vs $VPC_ID), will be recreated"
fi

for TF_NAME in billing_db inventory_db; do
  DB_SUFFIX=$(echo $TF_NAME | tr '_' '-')
  DB_ID="${PREFIX}-${DB_SUFFIX}"
  DB_EXISTS=$(aws rds describe-db-instances \
    --db-instance-identifier "$DB_ID" --region $REGION \
    --query 'DBInstances[0].DBInstanceIdentifier' --output text 2>/dev/null || echo "")
  import_if_exists "aws_db_instance.${TF_NAME}" "$DB_EXISTS"
done

# ── COGNITO ───────────────────────────────────
POOL_ID=$(aws cognito-idp list-user-pools --max-results 10 --region $REGION \
  --query "UserPools[?Name=='${PREFIX}-user-pool'] | [0].Id" \
  --output text 2>/dev/null || echo "")
import_if_exists "aws_cognito_user_pool.main" "$POOL_ID"

if [ -n "$POOL_ID" ] && [ "$POOL_ID" != "None" ]; then
  DOMAIN=$(aws cognito-idp describe-user-pool \
    --user-pool-id "$POOL_ID" --region $REGION \
    --query 'UserPool.Domain' --output text 2>/dev/null || echo "")
  import_if_exists "aws_cognito_user_pool_domain.main" "$DOMAIN"

  CLIENT_ID=$(aws cognito-idp list-user-pool-clients \
    --user-pool-id "$POOL_ID" --region $REGION \
    --query 'UserPoolClients[0].ClientId' --output text 2>/dev/null || echo "")
  import_if_exists "aws_cognito_user_pool_client.gateway" "${POOL_ID}/${CLIENT_ID}"
fi

# ── IAM ───────────────────────────────────────
ROLE_EXISTS=$(aws iam get-role \
  --role-name "${PREFIX}-ecs-task-execution-role" \
  --query 'Role.RoleName' --output text 2>/dev/null || echo "")
import_if_exists "aws_iam_role.ecs_task_execution" "${PREFIX}-ecs-task-execution-role"

POLICY_ARN=$(aws iam list-attached-role-policies \
  --role-name "${PREFIX}-ecs-task-execution-role" \
  --query "AttachedPolicies[?PolicyName=='AmazonECSTaskExecutionRolePolicy'] | [0].PolicyArn" \
  --output text 2>/dev/null || echo "")
import_if_exists "aws_iam_role_policy_attachment.ecs_task_execution" \
  "${PREFIX}-ecs-task-execution-role/${POLICY_ARN}"

# ── AUTOSCALING ───────────────────────────────
# Check with correct format: ServiceNamespace + ResourceId filter
AS_EXISTS=$(aws application-autoscaling describe-scalable-targets \
  --service-namespace ecs --region $REGION \
  --query "ScalableTargets[?ResourceId=='service/${PREFIX}-cluster/${PREFIX}-api-gateway-service'] | [0].ResourceId" \
  --output text 2>/dev/null || echo "")

if [ -n "$AS_EXISTS" ] && [ "$AS_EXISTS" != "None" ]; then
  # Correct import ID format: service-namespace/resource-id/scalable-dimension
  import_if_exists "aws_appautoscaling_target.gateway" \
    "ecs/service/${PREFIX}-cluster/${PREFIX}-api-gateway-service/ecs:service:DesiredCount"
else
  echo "⏭️  Skipping (not found): aws_appautoscaling_target.gateway"
fi

# ── SERVICE DISCOVERY ─────────────────────────
NS_ID=$(aws servicediscovery list-namespaces --region $REGION \
  --query "Namespaces[?Name=='${PREFIX}.local'] | [0].Id" \
  --output text 2>/dev/null || echo "")
import_if_exists "aws_service_discovery_private_dns_namespace.internal" "$NS_ID"

if [ -n "$NS_ID" ] && [ "$NS_ID" != "None" ]; then
  for TF_NAME in billing_db billing_queue inventory_app inventory_db; do
    SVC_NAME=$(echo $TF_NAME | tr '_' '-')
    SD_ID=$(aws servicediscovery list-services \
      --filters "Name=NAMESPACE_ID,Values=${NS_ID},Condition=EQ" --region $REGION \
      --query "Services[?Name=='${SVC_NAME}'] | [0].Id" \
      --output text 2>/dev/null || echo "")
    import_if_exists "aws_service_discovery_service.${TF_NAME}" "$SD_ID"
  done
fi

# ── SSM PARAMETERS ────────────────────────────
for PARAM_TF in billing_db_password inventory_db_password rabbitmq_password; do
  PARAM_NAME=$(echo $PARAM_TF | tr '_' '-')
  PARAM_EXISTS=$(aws ssm get-parameter \
    --name "/${PREFIX}/${PARAM_NAME}" --region $REGION \
    --query 'Parameter.Name' --output text 2>/dev/null || echo "")
  import_if_exists "aws_ssm_parameter.${PARAM_TF}" "/${PREFIX}/${PARAM_NAME}"
done

echo ""
echo "---"
echo "✅ imports.tf generated successfully"
cat $IMPORTS_FILE
